/*
 * This file is generated by jOOQ.
 */
package com.windyu.jooq.model;


import com.windyu.jooq.model.tables.JpHoliday;
import com.windyu.jooq.model.tables.records.JpHolidayRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<JpHolidayRecord> JP_HOLIDAY_PKEY = Internal.createUniqueKey(JpHoliday.JP_HOLIDAY, DSL.name("jp_holiday_pkey"), new TableField[] { JpHoliday.JP_HOLIDAY.HOL_DATE }, true);
}
