/*
 * This file is generated by jOOQ.
 */
package com.windyu.jooq.model;


import com.windyu.jooq.model.tables.JpHoliday;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.jp_holiday</code>.
     */
    public static final JpHoliday JP_HOLIDAY = JpHoliday.JP_HOLIDAY;
}
